use crate::math::decay::shift_decay_i8;
use crate::constants::{SOMATIC_DECAY, SOMA_V_RESET};

pub struct Soma {
    pub soma_potentials: Vec<i8>,
    pub soma_thresholds: Vec<i8>,
    pub soma_betas: Vec<u8>,
    pub soma_last_events: Vec<u16>,
    pub soma_lrs: Vec<i16>, // learning rates
    pub dendrite_offsets: Vec<u32>,
}

// applies lazy decay to the soma potential and adds v_s to it. Updates the last event timestamp.
// returns the number of APs generated by this update and resets the potential if APs are generated.
pub fn update_soma_potential(
    timestamp: u16,
    so_idx: usize,
    soma_potentials: &mut [i8],
    soma_last_events: &mut [u16],
    soma_thresholds: &[i8],
    soma_betas: &mut [u8],
    v_s : i16, // voltage change to apply to the soma potential
) -> u8 {
    let elapsed = timestamp.wrapping_sub(soma_last_events[so_idx]);
    let decayed_potential = shift_decay_i8(soma_potentials[so_idx], elapsed, SOMATIC_DECAY);
    soma_last_events[so_idx] = timestamp;

    let new_v = decayed_potential as i16 + v_s;
    if new_v >= soma_thresholds[so_idx] as i16 && soma_thresholds[so_idx] > 0 {
        let burst = new_v / (soma_thresholds[so_idx] as i16);
        soma_potentials[so_idx] = SOMA_V_RESET; // reset potential after spike
        soma_betas[so_idx] = soma_betas[so_idx].saturating_add(1); // increment burst term
        burst as u8
    } else {
        soma_potentials[so_idx] = new_v.clamp(i8::MIN as i16, i8::MAX as i16) as i8;
        0 // no AP generated
    }
    
}